spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:game-master
    username: root
    password:
  sql:
    init:
      mode: always
  # Configuração do H2
  h2:
    console:
      path: /h2-console
      enabled: true
  # JPA e SQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true